//index.js
Page({
  data:{
      usersList:[{name:"图灵机器人",src:"http://www.tuling123.com/resources/web/v4/img/personalCen/icon40.png",time:"12:00"}]
  },
  chat:function(){
      wx.navigateTo({url:"../chat/chat"})
  }
})
